export const ITINERARIES = [
  {
    id: 'night-owl',
    title: 'The Night Owl',
    tagline: '22h - 4h • Late Night Cravings',
    description: 'When the city slows down, the best food comes out. From "Trash Can Rice" to midnight noodles.',
    gradient: 'from-ube-800 to-blueberry-800',
    accent: 'ube-300',
    stops: [
      { time: '22:30', name: 'Cháo Trắng Hàng Xanh', type: 'Late Night Comfort', status: 'Active' },
      { time: '00:00', name: 'Hủ Tiếu Gõ Cô Ba', type: 'Street Food', status: 'Packing Up Soon' },
      { time: '02:00', name: 'Cơm Tấm Bãi Rác', type: 'Hidden Gem', status: 'Full House' },
    ]
  },
  {
    id: 'early-bird',
    title: 'The Early Bird',
    tagline: '05h - 10h • Sunrise & Steam',
    description: 'Start your day with the rhythmic clinking of coffee filters and the aroma of morning broth.',
    gradient: 'from-lemon-400 to-lemon-700',
    accent: 'lemon-800',
    stops: [
      { time: '05:30', name: 'Cà Phê Vợt Phan Đình Phùng', type: 'Traditional', status: 'Vibrant' },
      { time: '07:00', name: 'Bún Mọc Thanh Mai', type: 'Market Breakfast', status: 'Queuing' },
      { time: '09:00', name: 'Phở Bưng Vỉa Hè', type: 'Street Food', status: 'Running Out' },
    ]
  },
  {
    id: 'non-stop-challenge',
    title: '24h Non-stop Challenge',
    tagline: '8 Meals • 24 Hours • 1 Champion',
    description: 'The ultimate culinary marathon. 8 curated stops with optimized digestion breaks.',
    gradient: 'from-pomegranate-400 to-slushie-800',
    accent: 'matcha-300',
    stops: [
      { time: '08:00', name: 'Stop 1: Breakfast Phở', type: 'Start' },
      { time: '12:00', name: 'Stop 2: Lunch Bún Chả', type: 'Progress' },
      { time: '16:00', name: 'Stop 3: Afternoon Snacks', type: 'Progress' },
      { time: '19:00', name: 'Stop 4: Dinner BBQ', type: 'Progress' },
      // ... more stops
    ]
  },
  {
    id: 'district-9-night',
    title: 'Làng Đại Học Night',
    tagline: '22h - 5h • The Study Marathon',
    description: "District 9's legendary student life. From workspace cafes to silent corners for pre-exam grinds.",
    gradient: 'from-matcha-600 to-matcha-900',
    accent: 'matcha-300',
    stops: [
      { time: '22:00', name: 'TRẠM 24h', type: 'Workspace', status: 'Focused' },
      { time: '01:00', name: 'Créma Coffee 24h', type: 'Social Study', status: 'Full Capacity' },
      { time: '03:30', name: 'KATALI COFFEE', type: 'Chill Out', status: 'Quiet' },
    ]
  }
];

export const VENUES = [
{
    id: 1,
    name: "Hẻm 158 Pasteur",
    category: "Hidden Gem",
    isLocal: true,
    status: "Busy",
    coord: [10.776, 106.696],
    district: "District 1",
    open_at: "06:00",
    close_at: "22:00",
    review_score: 4.8,
    price_range: "$",
    is_hidden_gem: true,
    summary: "Tucked away in the neon-lit heartbeat of District 1, this 30-year legend offers a masterclass in noodle craft. This is the ultimate Must-eat Saigon secret—a true Hidden Gem tucked deep within the Pasteur alleys where noodle mastery meets the city's authentic soul."
  },
  {
    id: 2,
    name: "The Gantry",
    category: "Fine Dining",
    isLocal: false,
    status: "Booking Required",
    coord: [10.778, 106.702],
    district: "District 1",
    open_at: "11:00",
    close_at: "23:00",
    review_score: 4.9,
    price_range: "$",
    is_hidden_gem: false,
    summary: "Where the Saigon River breeze meets elevated culinary artistry. The Gantry transforms traditional Vietnamese flavors into a Fine Dining masterpiece. Experience the most sophisticated gastronomy in District 1, meticulously crafted for the modern global traveler."
  },
  {
    id: 3,
    name: "TRẠM 24h",
    category: "Street Food",
    isLocal: true,
    status: "Active",
    coord: [10.825, 106.765],
    district: "District 9",
    open_at: "00:00",
    close_at: "23:59",
    review_score: 4.2,
    price_range: "$",
    is_hidden_gem: true,
    summary: "The ultimate student sanctuary in Phước Long B. Quiet, spacious, and open forever."
  },
  {
    id: 4,
    name: "Trân Kỳ Coffee & Tea",
    category: "Hidden Gem",
    isLocal: true,
    status: "Vibrant",
    coord: [10.815, 106.775],
    district: "District 9",
    open_at: "00:00",
    close_at: "23:59",
    review_score: 4.6,
    price_range: "$",
    is_hidden_gem: true,
    summary: "Vintage aesthetics meet 24/7 convenience on Đỗ Xuân Hợp."
  },
  {
    id: 5,
    name: "KATALI COFFEE",
    category: "Street Food",
    isLocal: true,
    status: "Focused",
    coord: [10.840, 106.772],
    district: "District 9",
    open_at: "00:00",
    close_at: "23:59",
    review_score: 4.5,
    price_range: "$",
    is_hidden_gem: false,
    summary: "Modern vibes and strong energy on the busy Lê Văn Việt strip."
  },
  {
    id: 6,
    name: "WORKAHOLIC CAFE 24/7",
    category: "Hidden Gem",
    isLocal: true,
    status: "Quiet",
    coord: [10.845, 106.785],
    district: "District 9",
    open_at: "00:00",
    close_at: "23:59",
    review_score: 4.7,
    price_range: "$",
    is_hidden_gem: true,
    summary: "Dedicated co-working pods and a serious atmosphere for 'running deadlines'."
  },
  {
    id: 7,
    name: "Créma Coffee 24h",
    category: "Street Food",
    isLocal: true,
    status: "Social",
    coord: [10.842, 106.781],
    district: "District 9",
    open_at: "00:00",
    close_at: "23:59",
    review_score: 4.4,
    price_range: "$",
    is_hidden_gem: false,
    summary: "The heart of Man Thiện student life. Always bustling, always welcoming."
  },
  {
    id: 8,
    name: "Trà dâu Đông Du",
    category: "Street Food",
    isLocal: true,
    status: "Vibrant",
    coord: [10.776, 106.704],
    district: "District 1",
    open_at: "10:00",
    close_at: "23:00",
    review_score: 4.9,
    price_range: "$",
    is_hidden_gem: false,
    summary: "The legendary street tea that defines District 1 afternoons. Icy, sweet, and perfectly refreshing."
  },
  {
    id: 9,
    name: "Bánh tráng trộn chú Viên",
    category: "Street Food",
    isLocal: true,
    status: "Long Queue",
    coord: [10.768, 106.682],
    district: "District 3",
    open_at: "14:00",
    close_at: "21:00",
    review_score: 4.9,
    price_range: "$",
    is_hidden_gem: false,
    summary: "Often called the best mixed rice paper in the city. Expect a wait, but it's worth every second."
  },
  {
    id: 10,
    name: "Yes Cafe",
    category: "Hidden Gem",
    isLocal: true,
    status: "Active",
    coord: [10.875, 106.801],
    district: "District 9",
    open_at: "00:00",
    close_at: "23:59",
    review_score: 4.5,
    price_range: "$",
    is_hidden_gem: true,
    summary: "The legendary 'no-sleep' sanctuary behind KTX Khu A. Spacious, tech-friendly, and student-powered."
  },
  {
    id: 11,
    name: "Đông Du Coffee & Tea",
    category: "Hidden Gem",
    isLocal: true,
    status: "Active",
    coord: [10.873, 106.803],
    district: "District 9",
    open_at: "00:00",
    close_at: "23:59",
    review_score: 4.6,
    price_range: "$",
    is_hidden_gem: true,
    summary: "Vintage aesthetics and a quiet atmosphere perfect for late-night deadline marathons."
  },
  {
    id: 12,
    name: "B Coffee 24h",
    category: "Street Food",
    isLocal: true,
    status: "Active",
    coord: [10.87, 106.795],
    district: "District 9",
    open_at: "00:00",
    close_at: "23:59",
    review_score: 4.3,
    price_range: "$",
    is_hidden_gem: false,
    summary: "A reliable 24/7 hub for coffee and snacks in the heart of the student village."
  },
  {
    id: 13,
    name: "Giangnam Coffee",
    category: "Street Food",
    isLocal: true,
    status: "Active",
    coord: [10.865, 106.805],
    district: "District 9",
    open_at: "00:00",
    close_at: "23:59",
    review_score: 4.4,
    price_range: "$",
    is_hidden_gem: false,
    summary: "Industrial vibes and strong caffeine for the sunrise study sessions."
  },
  {
    id: 14,
    name: "KFC",
    category: "Street Food",
    isLocal: true,
    status: "Active",
    coord: [10.8483849, 106.7746746],
    district: "District 9",
    open_at: "08:00",
    close_at: "22:00",
    review_score: 4.7,
    price_range: "$",
    is_hidden_gem: false,
    summary: "Authentic fried_chicken spot discovered via OpenStreetMap."
  },
  {
    id: 15,
    name: "Nhà Hàng Đầm Tôm",
    category: "Street Food",
    isLocal: true,
    status: "Active",
    coord: [10.835471, 106.765147],
    district: "District 9",
    open_at: "08:00",
    close_at: "22:00",
    review_score: 4.8,
    price_range: "$",
    is_hidden_gem: false,
    summary: "Authentic restaurant spot discovered via OpenStreetMap."
  },
  {
    id: 16,
    name: "Cà Phê Amy",
    category: "Hidden Gem",
    isLocal: true,
    status: "Active",
    coord: [10.844939, 106.767218],
    district: "District 9",
    open_at: "08:00",
    close_at: "22:00",
    review_score: 4.6,
    price_range: "$",
    is_hidden_gem: true,
    summary: "Authentic coffee_shop spot discovered via OpenStreetMap."
  },
  {
    id: 17,
    name: "Bún Bò Thuận An 2",
    category: "Street Food",
    isLocal: true,
    status: "Active",
    coord: [10.844877, 106.767471],
    district: "District 9",
    open_at: "08:00",
    close_at: "22:00",
    review_score: 4.5,
    price_range: "$",
    is_hidden_gem: false,
    summary: "Authentic vietnamese spot discovered via OpenStreetMap."
  },
  {
    id: 18,
    name: "Cà Phê Nice",
    category: "Hidden Gem",
    isLocal: true,
    status: "Active",
    coord: [10.844476, 106.769729],
    district: "District 9",
    open_at: "08:00",
    close_at: "22:00",
    review_score: 4.6,
    price_range: "$",
    is_hidden_gem: true,
    summary: "Authentic cafe spot discovered via OpenStreetMap."
  },
  {
    id: 19,
    name: "Caffe Vườn Yêu",
    category: "Hidden Gem",
    isLocal: true,
    status: "Active",
    coord: [10.844518, 106.769922],
    district: "District 9",
    open_at: "08:00",
    close_at: "22:00",
    review_score: 4.5,
    price_range: "$",
    is_hidden_gem: true,
    summary: "Authentic cafe spot discovered via OpenStreetMap."
  },
  {
    id: 20,
    name: "Cà Phê 39A",
    category: "Hidden Gem",
    isLocal: true,
    status: "Active",
    coord: [10.816985, 106.832798],
    district: "District 9",
    open_at: "08:00",
    close_at: "22:00",
    review_score: 4.7,
    price_range: "$",
    is_hidden_gem: true,
    summary: "Authentic cafe spot discovered via OpenStreetMap."
  },
  {
    id: 21,
    name: "Nhà Hàng Lẩu Mắm Phong Lan",
    category: "Street Food",
    isLocal: true,
    status: "Active",
    coord: [10.813877, 106.83553],
    district: "District 9",
    open_at: "08:00",
    close_at: "22:00",
    review_score: 4.7,
    price_range: "$",
    is_hidden_gem: false,
    summary: "Authentic vietnamese spot discovered via OpenStreetMap."
  },
  {
    id: 22,
    name: "Quán Ăn Bờ Sông",
    category: "Street Food",
    isLocal: true,
    status: "Active",
    coord: [10.812372, 106.833108],
    district: "District 9",
    open_at: "08:00",
    close_at: "22:00",
    review_score: 4.8,
    price_range: "$",
    is_hidden_gem: false,
    summary: "Authentic restaurant spot discovered via OpenStreetMap."
  },
  {
    id: 23,
    name: "Lotteria",
    category: "Street Food",
    isLocal: true,
    status: "Active",
    coord: [10.8499193, 106.7680969],
    district: "District 9",
    open_at: "07:00",
    close_at: "23:00",
    review_score: 4.1,
    price_range: "$",
    is_hidden_gem: false,
    summary: "Authentic burger spot discovered via OpenStreetMap."
  }
];
